### ISSUE TITLE
which data base used by azure APIM for storing  FHIR Server data.

### ISSUE THREAD

**Issue by rameshkr1994** [hansenms/fhir2azureapim#2]
Hello @hansenms 

which data base used by azure APIM for storing the data for FHIR Server.

we are able to create Azure APIM for FHIR Server but we are not able to see any data bases inside 
Azure APIM .only showing something RU.

so could you please help me 

Thanks
HadoopHelp

**Comment by hansenms** [comment]
It uses whatever FHIR server it is front-ending. When you say Azure APIM, what do you mean? If you are talking about the managed Azure API for FHIR (https://docs.microsoft.com/en-us/azure/healthcare-apis/) then the database is an implementation detail. You do not have direct access to the database. APIM, as in Azure API Management, is just a proxying layer that you can, optionally put in front of a FHIR server.

I don't think there is anything actionable here, so I will close this out.
